#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-stub-runner.name" . }}
  labels:
    {{- include "eric-oss-stub-runner.labels" . | indent 4 }}
    {{- include "eric-oss-stub-runner.config-labels" . | indent 4 }}
  annotations:
    {{- include "eric-oss-stub-runner.product-info" . | indent 4 }}
    {{- include "eric-oss-stub-runner.config-annotations" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "eric-oss-stub-runner.selectorLabels" . | nindent 4 }}
