#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

version: 3
cli:
  server: https://scasfossa-staging.internal.ericsson.com
  fetcher: custom
  project: eric-oss-5gcnr
analyze:
  modules:
  - name: eric-oss-cnr5gassist
    type: mvn
    target: pom.xml
    path: .
