#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

spring.jackson.default-property-inclusion: "non_null"

management.endpoints.enabled-by-default: "false"
management.endpoint.health.enabled: "true"
management.endpoint.info.enabled: "true"
management.endpoint.metrics.enabled: "true"
management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: "true"
management.info.env.enabled: "true"
management.metrics.export.prometheus.enabled: "true"
management.metrics.web.server.request.autotime.enabled: "true"
#opentracing.jaeger.enabled: "true"

endpoints.health.sensitive: "false"
info.app.name: '@name@'
info.app.description: "Main service of 5G CNR rApp"
info.app.version: '@version@'
info.app.legal: "COPYRIGHT Ericsson 2021 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.4.2/reference/html/spring-boot-features.html#boot-features-custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
#stubrunner.username: <LAN SIGNUM ID>
#stubrunner.password: <LAN encrypted PWD or JFrog API Key>
stubrunner.username: ${SELI_ARTIFACTORY_REPO_USER}
stubrunner.password: ${SELI_ARTIFACTORY_REPO_PASS}

gateway.scheme: ${GATEWAY_SCHEME:http}
gateway.host: ${GATEWAY_HOST:localhost}
gateway.port: ${GATEWAY_PORT:}
gateway.insecure: ${GATEWAY_INSECURE:false}
gateway.auth.login: ${GATEWAY_AUTH_LOGIN:}
gateway.auth.password: ${GATEWAY_AUTH_PASSWORD:}
gateway.auth.tenant: ${GATEWAY_AUTH_TENANT:master}
gateway.auth.session: ${GATEWAY_AUTH_SESSION:}
gateway.auth.refresh-period: ${GATEWAY_AUTH_REFRESH_PERIOD:1800}
gateway.retry.maxAttempts: ${RETRY_MAX_ATTEMPTS:3}
gateway.retry.maxDelay: ${RETRY_MAX_DELAY:1000}
gateway.retry.maxDelayEnmOverload: ${RETRY_MAX_DELAY_OVERLOAD:50000}
gateway.services.cts.url: ${CTS_URL:}
gateway.services.cts.base-path: ${CTS_BASE_PATH:}
gateway.services.cts.headers: ${CTS_HEADERS:}
gateway.services.ncmp.url: ${NCMP_URL:}
gateway.services.ncmp.base-path: ${NCMP_BASE_PATH:}
gateway.services.ncmp.headers: ${NCMP_HEADERS:}

metric.uniqueAppId: "app_name"
metric.instance: "instance_name"

nrc.thread-pool-size: 1
nrc.thread-queue-size: 10
nrc.history-size: 100
nrc.cache.max-size: 200
nrc.cache.expiry-time: 600

logging:
  config: ${LOGBACK_CONFIG_FILE:classpath:logback-json.xml}
  endpoints:
    exclude: /actuator/health, /actuator/prometheus, /ping, /metrics, /actuator/id-(.*)
  logcontrol-file: ${LOG_CTRL_FILE:/logcontrol/logcontrol.json}

spring.autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration