#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

openapi: "3.0.2"
info:
  title: "5G CNR CTS Client schemas"
  description: "OpenAPI file which contains responses for 5G CNR CTS Client"
  version: "0.0.1"
  license:
    name: "COPYRIGHT Ericsson 2021"
    url: "https://www.ericsson.com/en/legal"
  termsOfService: "https://www.ericsson.com/en/legal"
components:
  responses:
    BadRequest:
      description: "BAD REQUEST"
      content:
        application/json:
          schema:
            $ref: ./eric-topology-handling.schemas.openapi.yaml#/components/schemas/GraniteFaultStack
