#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $global := fromJson (include "eric-oss-5gcnr-test.global" .) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eric-oss-5gcnr-test-k6.main
  labels:
    {{- include "eric-oss-5gcnr-test.labels" $ | indent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      labels:
        {{- include "eric-oss-5gcnr-test.labels" $ | indent 8 }}
    spec:
      {{- include "eric-oss-5gcnr-test.pullSecret" $ | indent 6 }}
      containers:
      - name: test
        image: {{ include "eric-oss-5gcnr-test.image" $ }}
        imagePullPolicy: IfNotPresent
        resources: {{- toYaml $.Values.resources | nindent 10 }}
        env:
        - name: SERVICE_SCHEMA
          value: "http"
        - name: SERVICE_HOST
          value: {{ $.Values.cnr5gmain.name | quote }}
        - name: SERVICE_PORT
          value: {{ $.Values.cnr5gmain.port | quote }}
        - name: APIGW_HOST
          value: {{ $global.hosts.pf }}
        - name: TZ
          value: $global.timezone
        - name: STAGING_LEVEL
          value: {{ include "eric-oss-5gcnr-test.productStaging" $ | quote }}
      restartPolicy: Never
