#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
data:
  logcontrol.json: |-
    [
      {
        "container": "eric-oss-cnr5gassist",
        "severity": {{ .Values.logging.logLevel | quote}}
      }
    ]
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-5gcnr.name" . }}-log-control-configmap
  labels:
    {{- include "eric-oss-5gcnr.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-5gcnr.annotations" . | nindent 4 }}
