{{- if not .Values.integration.policyFramework.secretName }}
#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "eric-oss-5gcnr.name" . }}
  labels:
    {{- include "eric-oss-5gcnr.labels" . | nindent 4 }}
  annotations:
  {{- $default := include "eric-oss-5gcnr.annotations" . | fromYaml -}}
  {{- $helmHooks := dict -}}
  {{- $_ := set $helmHooks "helm.sh/hook" "pre-install, pre-upgrade" -}}
  {{- $_ := set $helmHooks "helm.sh/hook-weight" "0" -}}
  {{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "before-hook-creation" -}}
  {{- include "eric-oss-5gcnr.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $default)) | nindent 4 }}
data:
{{- range $key, $value := .Values.integration.policyFramework.credentials }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}