#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-5gcnr.fullname" . }}
  labels:
    {{- include "eric-oss-5gcnr.labels" . | nindent 4 }}
  annotations:
    {{- $default := include "eric-oss-5gcnr.annotations" . | fromYaml -}}
    {{- $prometheus := include "eric-oss-5gcnr.prometheus" . | fromYaml -}}
    {{- include "eric-oss-5gcnr.mergeAnnotations" (dict "location" .Template.Name "sources" (list $prometheus $default)) | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if (include "eric-oss-5gcnr.internalIPFamily" .) }}
  ipFamilies: [{{- include "eric-oss-5gcnr.internalIPFamily" . | quote }}]
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "eric-oss-5gcnr.selectorLabels" . | nindent 4 }}