#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

documents:
  - name: "User Guide"
    filepath: build/doc/html/user-guide.zip
  - name: "API Documentation"
    filepath: build/doc/html/API_Definition/index.html
  - name: "Secure Coding Report"
    external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffcacb7839?docno=10565-APR201618/1Uen&action=current&format=msw12
    restricted: true
  - name: "RA & PIA Report"
    external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffcaab8813?docno=00664-APR201618/1Uen&action=approved&format=msw12me
    restricted: true
  - name: "Test Report"
    external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffcb02c5f1?docno=1/15283-APR201618/1Uen&action=current&format=pdf
    restricted: true
  - name: "Characteristic Summary Report"
    external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffcb2b21e0?docno=2/15283-APR201618/1Uen&action=current&format=pdf
    restricted: true
  - name: "k6 Test Plan"
    external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffcb075b41?docno=1/15281-APR201618/1Uen&action=current&format=html
    restricted: true
  - name: "Software Vendor List (SVL)"
    filepath: doc/target/generated-docs/svl/3pp_list.xlsx