{{- if eq (include "eric-oss-5gcnr.hook.register" .) "true" }}
#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $global := fromJson (include "eric-oss-5gcnr.global" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-oss-5gcnr.name" . }}-delete-route
  labels:
    {{- include "eric-oss-5gcnr.labels" . | indent 4 }}
    {{- include "eric-oss-5gcnr.config-labels" . | indent 4 }}
  annotations:
    {{- include "eric-oss-5gcnr.product-info" . | indent 4 }}
    {{- include "eric-oss-5gcnr.config-annotations" . | indent 4 }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    {{- include "eric-oss-5gcnr.service-mesh-hook-annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      labels: {{- include "eric-oss-5gcnr.config-labels" . | nindent 8 }}
      annotations: {{- include "eric-oss-5gcnr.config-annotations" . | nindent 8 }}
    spec:
      {{- if include "eric-oss-5gcnr.pullSecret" . }}
      imagePullSecrets:
      - name: {{ include "eric-oss-5gcnr.pullSecret" . | quote }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: eric-api-gateway-client
        {{- $image2 := merge (dict "imageName" "eric-api-gateway-client") . }}
        image: {{ include "eric-oss-5gcnr.image" $image2 }}
        imagePullPolicy: {{ include "eric-oss-5gcnr.imagePullPolicy" $image2 }}
        env:
          - name: PF_HOST
            value: {{ include "eric-oss-5gcnr.global.hostUrl" (merge (dict "host" "pf") .) | quote }}
          - name: PF_SYSTEM_USER
            valueFrom:
              secretKeyRef:
                name: {{ $global.systemUser.secret | quote }}
                key: {{ $global.systemUser.userKey | quote }}
          - name: PF_SYSTEM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $global.systemUser.secret | quote }}
                key: {{ $global.systemUser.passwordKey | quote }}
        args:
          - "-insecure"
          - "$(PF_HOST)"
          - "$(PF_SYSTEM_USER)"
          - "$(PF_SYSTEM_PASSWORD)"
          - "delete"
          - "{{ include "eric-oss-5gcnr.fullname" . | replace "-" "_" }}_route"
        {{- with index .Values "resources" "eric-api-gateway-client" }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - name: {{ include "eric-oss-5gcnr.name" . }}-deregister-app-config-volume
            mountPath: /config
          - name: create-cacert-volume
            mountPath: /mnt/certs
      volumes:
      - name: {{ include "eric-oss-5gcnr.name" . }}-deregister-app-config-volume
        configMap:
          name: {{ include "eric-oss-5gcnr.name" . }}-deregister-app-config
          defaultMode: 0777
      - name: create-cacert-volume
        secret:
          secretName: {{ $global.iam.cacert.secretName }}
          items:
          - key: {{ $global.iam.cacert.key }}
            path: {{ $global.iam.cacert.filePath }}
{{- end }}
